### PR TITLE
Fix undefined method `[]=' for nil:NilClass

### PR DESCRIPTION
**Pull request by bdunne**
Introduced in #433

### CODE REVIEW

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit deadca597cb0656d5865b013f2e269a2b915d579
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Wed Jul 29 11:03:24 2020 -0400

    Merge pull request #434 from bdunne/undefined_method

    Fix undefined method `[]=' for nil:NilClass

    (cherry picked from commit cce6bd3b89e50aa0e028d2adebabaf232a158209)
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit f4ede235849534cd5291125217d059248f0e627e
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Wed Jul 29 11:03:24 2020 -0400

    Merge pull request #434 from bdunne/undefined_method

    Fix undefined method `[]=' for nil:NilClass

    (cherry picked from commit cce6bd3b89e50aa0e028d2adebabaf232a158209)
```
